### ISSUE TITLE
messages not stored?

### ISSUE THREAD

**Issue by brunoqc** [slact/nchan#136] opened 2016-02-23 14:59 UTC
I'm not sure if it's a bug. I wouldn't be surprised if I didn't read/understand the doc properly.

I want to publish a message first and then getting it when I connect as a subscriber after. Right now I don't get "123" with the second curl command.
```sh
$ curl --request POST --data "123" http://localhost/pub/test
queued messages: 1
last requested: 0 sec. ago
active subscribers: 0
last message id: 1456239531:0
$ curl http://localhost/sub/test # blocks (is waiting)
```

My user case is that I have displays that show a counter that increments during the day. I would like them to get the new value when I publish one and I would like them to get the freshest value when they connect. I only would like to keep the freshest value in the nchan queue since I only care about the new counter value.

That's why I set `nchan_message_buffer_length` to 1. I set `nchan_message_timeout` to 0 since I don't want the message to expire.

nginx.conf
```
worker_processes auto;

events {
    worker_connections  1024;
}

http {
    server {
        listen 80 default;

        location ~ /sub/(\w+)$ {
            #channel id is the word after /sub/
            # GET /sub/foobar_baz will have the channel id set to 'foobar_baz'
            # I hope you know your regular expressions...
            nchan_subscriber;
            nchan_channel_id $1; #first capture of the location match
        }

        location ~ /pub/(\w+)$ {
            #channel id is the word after /sub/
            # GET /sub/foobar_baz will have the channel id set to 'foobar_baz'
            # I hope you know your regular expressions...
            nchan_publisher;
            nchan_channel_id $1; #first capture of the location match
            nchan_message_buffer_length 1;
            nchan_message_timeout 0;
        }
    }
}
```

I run it with:
```sh
docker run -p 80:80 -v ~/test/nginx.conf:/etc/nginx/nginx.conf:ro bbigras/alpine-nginx-nchan
```

**Comment by brunoqc** [comment] 2016-02-23 15:36
It seems to work as I expect if I remove `nchan_message_timeout 0`.

**Comment by slact** [comment] 2016-02-23 17:20
`nchan_message_timeout 0` was being handled incorrectly. The issue is now fixed in master. You can use `nchan_message_timeout 1y` or some other large value for the same effect.

**Closed by slact** 2016-02-23 17:20 UTC
