### ISSUE TITLE
nginx "reload" issue with websocket subscriber

### ISSUE THREAD

**Issue by kmansoft** [slact/nchan#145] opened 2016-03-08 22:06 UTC
Running nginx 1.8.1 source with _only_ your plugin added, on my dev. system.

Found an issue with "reload"-ing nginx, seems like you're already aware of at least something related to reloading (cf: reloadbug brach), but wanted to provide additional info just in case.

Steps:

1 - Started nginx, opened an .html page (from a file) which creates a WebSocket connection.

2 - Published a change with curl "POST" -> received by WebSocket, appeared on the .html page

3 - nginx -s reload

4 - Published another change with curl "POST"

Effects:

1 - The WebSocket does not receive the new message

2 - An nginx process stuck at "R" state, with 100% CPU usage.

The process name is "nginx: worker process is shutting down"

3 - The below in nginx's error log.

```
2016/02/29 23:18:04 [error] 31623#0: MEMSTORE:00: 1 channels still present in reaper at exit  (slot 0)
2016/02/29 23:18:04 [error] 31623#0: MEMSTORE:00: 1 messages still present in reaper at exit  (slot 0)
2016/02/29 23:23:08 [error] 32197#0: MEMSTORE:00: 1 channels still present in reaper at exit  (slot 0)
2016/03/04 14:19:14 [error] 5536#0: OUTPUT:what's the deal with this NGX_HTTP_LOWLEVEL_BUFFERED thing?
2016/03/04 14:20:00 [notice] 6496#0: signal process started
2016/03/04 14:20:00 [error] 6431#0: MEMSTORE:01: 1 channels still present in reaper at exit  (slot 1)
2016/03/04 14:20:52 [error] 6497#0: MEMSTORE:02: 1 channels still present in reaper at exit  (slot 2)
2016/03/04 14:20:55 [alert] 5535#0: worker process 5536 exited on signal 9
2016/03/04 14:20:59 [notice] 6562#0: signal process started
2016/03/04 14:20:59 [error] 6562#0: open() "local/logs/nginx.pid" failed (2: No such file or directory)
2016/03/09 00:58:00 [notice] 28602#0: signal process started
2016/03/09 00:58:03 [error] 28487#0: OUTPUT:what's the deal with this NGX_HTTP_LOWLEVEL_BUFFERED thing?
```

**Comment by slact** [comment] 2016-03-09 00:24
This sounds a lot like #142 . I'd like some more information:

- What OS?
- How many CPU cores, and approximately what speed? Virtualized or real metal?
- Can you show me your nginx config? Edit out whatever you need to keep private.
- what is your Nchan usage pattern?
- how consistently reproducible is this issue?

Would it be possible for me to take a look at your server? Send me an email to nchan@slact.net and we could arrange a time convenient for you.

**Comment by kmansoft** [comment] 2016-03-09 10:05
I'm just experimenting on my development machine, so 1) this is not a server 2) there is no load other than those few curl requests and a WebSocket and 3) the page itself is loaded from disk as a file:// URL, no nginx does not handle anything else.

- Fedora 23 x64, kernel 4.4, Chrome latest 49.0.2623.75 (64-bit)
- Intel 6770 real metal, 16 GB of RAM
- nginx is from their source repo, the release-1.8.1 tag
- nchan is from github, commit ca993d31551c4663167ee34496c228f2b48937aa, release v0.99.6
- nchan is the only plugin, SSL support is enabled but not used:
```
$ ./objs/nginx -V
nginx version: nginx/1.8.1
built by gcc 5.3.1 20151207 (Red Hat 5.3.1-2) (GCC) 
configure arguments: --add-module=../nchan/ --with-openssl=/usr/local/ssl
```
- full nginx config: https://gist.github.com/kmansoft/49098dd975f43e87e7d0
- I only added this:
```
        # pub/sub test
                location = /sub {
                        nchan_subscriber;
                        nchan_channel_id foobar;
                        nchan_websocket_ping_interval 300;
                }

                location = /pub {
                        nchan_publisher;
                        nchan_channel_id foobar;
                        nchan_message_buffer_length 1;
                }
```
- test page source code: https://gist.github.com/kmansoft/41d6719cffdf781160af
- the "reconnecting websocket . js" there is this: https://github.com/joewalnes/reconnecting-websocket but don't think it's necessary

It's very easy for me to reproduce, takes less than a minute, and very consistent (haven't had it not happen, just did it twice while writing this comment):

- start nginx:
```$ ./objs/nginx -p local/ -c conf/nginx.conf```
- publish a message:
```$ curl --request POST --data "Test message 1" -H "Accept: text/json" http://127.0.0.1:8080/pub```
- open the test.html using a file:// URL in Chrome, it shows the just published message
- reload nginx:
```$ ./objs/nginx -s reload -p local/ -c conf/nginx.conf```
at this point, we're still good
- publish another message:
```$ curl --request POST --data "Test message 2" -H "Accept: text/json" http://127.0.0.1:8080/pub```

BLAM!

- nginx log has this now:
```
2016/03/09 12:52:08 [error] 3806#0: OUTPUT:what's the deal with this NGX_HTTP_LOWLEVEL_BUFFERED thing?
```
- ```nginx: worker process is shutting down``` is stuck at 100% CPU usage
- Chrome becomes unresponsive, all pages (even this one where I'm writing  this comment)
- sending SIGTERM to nginx outputs this into the error log:
```
2016/03/09 12:53:11 [error] 3987#0: MEMSTORE:01: 1 channels still present in reaper at exit  (slot 1)
```

Since this is my personal development system and not a server, I won't be able to provide access.

However, given that the whole config and the steps are so simple, and it's very predictable, I hope you should be able to reproduce it too.

Maybe -- by rookie luck -- somehow I've configured things so that this bug is really easy to trigger?

**Comment by slact** [comment] 2016-03-09 11:27
Thanks for the details. So far I can't reproduce this on an arch linux machine. Will try on Fedora next.

**Comment by kmansoft** [comment] 2016-03-09 11:34
Hmm.... With my configs and test.html?

If you are unable to repro on Fedora -- I just had a thought -- maybe I could try creating a separate user account for you to use on my computer. I will also now try to repro on a VPS running Debian (if I can get the binary to run there).

**Comment by slact** [comment] 2016-03-09 11:40
Ok, I'm able to replicate this under Fedora. I'll update this as I figure it out.

**Comment by kmansoft** [comment] 2016-03-09 11:48
Great!

**Comment by kmansoft** [comment] 2016-03-09 17:03
Also happens on Debian (Jesse stable, 8.3) running inside KVM on same (my personal development) computer.

KVM config:
```
qemu-kvm -cpu host -smp 4 -m 2048 -vga std -redir tcp:2222::22 -redir tcp:8081::8080 -drive file=jesse-amd64.img,if=virtio
```

I had to build nginx + nchan from source inside the KVM, as my binary from Fedora wouldn't run there (needs different .so's).

The websocket port 8081 is redirected into inside the KVM (```-redir tcp:8081::8080```), Chrome and curl commands are run on the host (outside the KVM).

```
2016/03/09 19:56:15 [notice] 1041#0: signal process started
2016/03/09 19:56:20 [error] 752#0: OUTPUT:what's the deal with this NGX_HTTP_LOWLEVEL_BUFFERED thing?
2016/03/09 19:56:55 [error] 752#0: OUTPUT:what's the deal with this NGX_HTTP_LOWLEVEL_BUFFERED thing?
2016/03/09 19:57:23 [error] 752#0: MEMSTORE:00: 1 channels still present in reaper at exit  (slot 0)
2016/03/09 19:57:23 [alert] 752#0: *2 open socket #3 left in connection 3
```

I don't recall seeing ```open socket #3 left in connection``` on Fedora, but by that time things have already gone wrong.

The "dying" nginx worker at 100% CPU is present too.

**Comment by slact** [comment] 2016-03-09 21:44
Ok, this should be fixed in master. Please take a look and let me know if this fixed it for you. The problem was a websocket ping loop due to incorrect handling of the ping event.

**Comment by kmansoft** [comment] 2016-03-09 23:02
Fixed: 100%, Chrome freezing, tested on both Fedora 23 and Debian (KVM).

Thank you!

The WebSocket gets closed by the "reload", is this normal?

Also this in the error log, a few seconds after the reloading, is this normal or indicates some other issue?

2016/03/10 02:00:49 [notice] 4010#0: signal process started
2016/03/10 02:00:51 [error] 4008#0: MEMSTORE:01: 1 channels still present in reaper at exit  (slot 1)
2016/03/10 02:00:51 [alert] 4008#0: *3 open socket #3 left in connection 4
2016/03/10 02:00:51 [alert] 4008#0: aborting

**Comment by slact** [comment] 2016-03-09 23:24
> The WebSocket gets closed by the "reload", is this normal?

Yes, a reload is expected to close connections. I may at some point be able to change this, but for now that is the expected behavior.

**Comment by kmansoft** [comment] 2016-03-09 23:25
Thank you for the clarification.

What about these?

```
2016/03/10 02:00:49 [notice] 4010#0: signal process started
2016/03/10 02:00:51 [error] 4008#0: MEMSTORE:01: 1 channels still present in reaper at exit (slot 1)
2016/03/10 02:00:51 [alert] 4008#0: *3 open socket #3 left in connection 4
2016/03/10 02:00:51 [alert] 4008#0: aborting
```

**Comment by slact** [comment] 2016-03-10 00:02
> 2016/03/10 02:00:51 [error] 4008#0: MEMSTORE:01: 1 channels still present in reaper at exit (slot 1)

That's the one I need to downgrade to a warning or notice or alert

> 2016/03/10 02:00:51 [alert] 4008#0: *3 open socket #3 left in connection 4

That's the one that's just aesthetics.

The other two are standard nginx runtime messages

**Closed** 2016-03-10 11:36 UTC
