### ISSUE TITLE
Redis connection lost issue.

### ISSUE THREAD

**Issue by saurabhguptag** [slact/nchan#371] opened 2017-07-04 12:19 UTC
On restarting redis server, you see that nginx has re-establish new connection with redis but it fails to push messages to subscribed users. On restarting nginx behavior goes normal. 

Is it expected to restart nginx once redis restarted?
But I see the new Connections being established between them so should not be the case.

**Comment by slact** [comment] 2017-07-04 17:47
can you show me your nginx config? you can edit out whatever you need to keep private.

**Comment by saurabhguptag** [comment] 2017-07-05 09:26
hi here is the config. just to say nchan.example.com is pointing to localhost

`upstream local_redis {
		nchan_redis_server "redis://localhost";
    }
	
	server {
		ssl_protocols TLSv1 TLSv1.1 TLSv1.2;	
		listen	localhost:443 ssl http2;
		
		server_name		nchan.example.com;
		
		root                    /home/example/projects/testing/nchan;
		
		ssl on;
		ssl_certificate                /etc/ssl/example/nchan.example.com.crt;
		ssl_certificate_key            /etc/ssl/example/nchan.example.com.key;
		ssl_prefer_server_ciphers 		on;
		
			
		location /nchan_stub_status {
			nchan_stub_status;
		}
			
		location = /sub {
			nchan_redis_pass local_redis;
			nchan_subscriber_first_message 1;
			nchan_subscriber;
			nchan_subscriber_last_message_id $http_last_event_id;
			nchan_channel_id $arg_id "${arg_id}score" "${arg_id}comm";
		}

		location = /pub {
			nchan_redis_pass local_redis;
			nchan_message_buffer_length 5;
			nchan_publisher;
			nchan_channel_id $arg_id;
			if ($arg_id  ~* "(.*)score") {
				nchan_eventsource_event "score";
			}
			if ($arg_id  ~* "(.*)comm") {
				nchan_eventsource_event "comm";
			}
		}
	}`

**Comment by slact** [comment] 2017-07-06 17:20
Are you using a Redis *cluster* or a *master* server at `redis://localhost`?

**Comment by saurabhguptag** [comment] 2017-07-10 06:26
just simple redis-server

**Comment by saurabhguptag** [comment] 2017-07-14 07:48
hi slact were you able to replicate the issue?

**Comment by slact** [comment] 2017-07-14 22:46
I have been unable to reproduce this issue. If you are using long-polling, this may  be related to the other issue you posted about regarding the `410 Gone` HTTP status code.

**Comment by saurabhguptag** [comment] 2017-07-20 09:22
Issue is independent of type of request. I believe i should make a video and share the issue.

**Comment by slact** [comment] 2017-11-25 23:02
Please reopen if you have more information. Closing for now.,

**Closed by slact** 2017-11-25 23:02 UTC
