### ISSUE TITLE
get_msg_from_msgkey_callback takes long time.

### ISSUE THREAD

**Issue by supertong** [slact/nchan#240] opened 2016-08-29 03:52 UTC
Hey @slact , me again :).
I ran into an issue where sometime the Nchan stop serving message to subscribers. It tooks me a while to find out how to reproduce the issue.

It happens when the message data size is greater than `5 * 1024` in `publish.lua`. In this case, Nchan will get the data in through `get_message_from_key.lua`. The problem happens because it takes tooooo long to get the message. Here is the log I got.
```
2016/08/29 03:29:59 [error] 790#0: REDISTORE: get_msg_from_msgkey_callback
2016/08/29 03:29:59 [error] 790#0: REDISTORE: redis command get_message_from_key took 206123 msec
2016/08/29 03:29:59 [error] 790#0: REDISTORE: got pinged
2016/08/29 03:30:13 [error] 790#0: REDISTORE: Get message from msgkey {channel:vision/vision-live-data}:msg:1472441413:0
192.168.99.1 - - - [29/Aug/2016:03:30:13 +0000] "POST /live-data/pub/snapshot HTTP/1.1" 200 102 "-" "-" 0.010
q2016/08/29 03:33:59 [error] 790#0: REDISTORE: get_msg_from_msgkey_callback
2016/08/29 03:33:59 [error] 790#0: REDISTORE: redis command get_message_from_key took 225735 msec
2016/08/29 03:33:59 [error] 790#0: REDISTORE: got pinged
```

and when there are more this kind of big data comes in at same time, the time takes "forever" and Nchan somehow seems keep waiting on this message and subsequent publish doesn't get published to subscribers.

Personally, I feel the `2016/08/29 03:33:59 [error] 790#0: REDISTORE: got pinged` is very interesting here. It makes me feel like the data is actually buffered somewhere and this `got pinged` flushed the data through.

Not sure if it's caused by hiredis. Does this ring a bell to you?

Cheers

**Comment by slact** [comment] 2016-08-29 04:05
Could you get me the output of nchan_stub_status while the message is being received, and afterwards?

At very high load, I've noticed that hiredis seems to stop processing incoming commands until it is "jolted awake" by sending a command -- or something like that. I've only seen this happen twice and I've been unable to reproduce it yet, but there's definitely something there.

**Comment by supertong** [comment] 2016-08-29 04:13
Before the big data sent
```
total published messages: 0
stored messages: 1
shared memory used: 44K
channels: 1
subscribers: 1
redis pending commands: 0
redis connected servers: 1
total interprocess alerts received: 0
interprocess alerts in transit: 0
interprocess queued alerts: 0
total interprocess send delay: 0
total interprocess receive delay: 0
```
While waiting for the message
```
total published messages: 1
stored messages: 2
shared memory used: 44K
channels: 1
subscribers: 1
redis pending commands: 1
redis connected servers: 1
total interprocess alerts received: 0
interprocess alerts in transit: 0
interprocess queued alerts: 0
total interprocess send delay: 0
total interprocess receive delay: 0
```

After the message received.
```
total published messages: 1
stored messages: 3
shared memory used: 72K
channels: 1
subscribers: 1
redis pending commands: 0
redis connected servers: 1
total interprocess alerts received: 0
interprocess alerts in transit: 0
interprocess queued alerts: 0
total interprocess send delay: 0
total interprocess receive delay: 0
```

Logs
```
2016/08/29 04:09:15 [error] 792#0: REDISTORE: redis command get_message took 100 msec
192.168.99.1 - - - [29/Aug/2016:04:09:29 +0000] "GET /stub HTTP/1.1" 200 322 "-" "curl/7.43.0" 0.000
192.168.99.1 - - - [29/Aug/2016:04:09:30 +0000] "GET /stub HTTP/1.1" 200 322 "-" "curl/7.43.0" 0.000
192.168.99.1 - - - [29/Aug/2016:04:09:31 +0000] "GET /stub HTTP/1.1" 200 322 "-" "curl/7.43.0" 0.000
192.168.99.1 - - - [29/Aug/2016:04:09:32 +0000] "GET /stub HTTP/1.1" 200 322 "-" "curl/7.43.0" 0.000
192.168.99.1 - - - [29/Aug/2016:04:09:33 +0000] "GET /stub HTTP/1.1" 200 322 "-" "curl/7.43.0" 0.000
2016/08/29 04:09:39 [error] 792#0: REDISTORE: Get message from msgkey {channel:vision/vision-live-data}:msg:1472443779:0
192.168.99.1 - - - [29/Aug/2016:04:09:39 +0000] "POST /live-data/pub/snapshot HTTP/1.1" 200 103 "-" "-" 0.011
192.168.99.1 - - - [29/Aug/2016:04:09:46 +0000] "GET /stub HTTP/1.1" 200 322 "-" "curl/7.43.0" 0.000
192.168.99.1 - - - [29/Aug/2016:04:09:49 +0000] "GET /stub HTTP/1.1" 200 322 "-" "curl/7.43.0" 0.000
192.168.99.1 - - - [29/Aug/2016:04:09:56 +0000] "GET /stub HTTP/1.1" 200 322 "-" "curl/7.43.0" 0.000
192.168.99.1 - - - [29/Aug/2016:04:10:24 +0000] "GET /stub HTTP/1.1" 200 322 "-" "curl/7.43.0" 0.000
192.168.99.1 - - - [29/Aug/2016:04:10:28 +0000] "GET /stub HTTP/1.1" 200 322 "-" "curl/7.43.0" 0.000
192.168.99.1 - - - [29/Aug/2016:04:10:53 +0000] "GET /stub HTTP/1.1" 200 322 "-" "curl/7.43.0" 0.000
192.168.99.1 - - - [29/Aug/2016:04:12:18 +0000] "GET /stub HTTP/1.1" 200 322 "-" "curl/7.43.0" 0.000
2016/08/29 04:12:28 [error] 792#0: REDISTORE: get_msg_from_msgkey_callback
2016/08/29 04:12:28 [error] 792#0: REDISTORE: redis command get_message_from_key took 169501 msec
2016/08/29 04:12:28 [error] 792#0: REDISTORE: got pinged
192.168.99.1 - - - [29/Aug/2016:04:12:32 +0000] "GET /stub HTTP/1.1" 200 322 "-" "curl/7.43.0" 0.000
```

**Comment by slact** [comment] 2016-08-29 04:16
Looks like I have some nginx<->hiredis adapter debugging to do.

**Comment by supertong** [comment] 2016-08-29 04:17
This is the data I sent though
```
const largeBlock = 'I am a Big Chunk Of Data'.repeat(1024);
```
hope this will help you to reproduce the issue.

**Comment by slact** [comment] 2016-08-29 05:42
Ok, fixed in abb9d65. This was sort of a bug in hiredis. It reads from the socket in 16KB increments, and doesn't check if there's more data left to read (https://github.com/redis/hiredis/blob/master/hiredis.c#L794-L820) . The event loop is supposed to notify hiredis that there is more data available, but the nginx loop doesn't do that.

**Comment by supertong** [comment] 2016-08-29 05:59
wow, you are fast. Thanks! I will have a try.

**Comment by slact** [comment] 2016-08-29 06:39
Well, looks like my fix isn't robust enough. Without hacking hiredis, I need to call `ioctl(ac->c.fd, FIONREAD, &bytes_left)` after every redis socket read(). I'm benchmarking how much overhead this adds.

**Comment by supertong** [comment] 2016-08-29 06:41
lol, was going to say that it's not working. But it seems to be working if I change the code to be like this
```
if (c->reader->len >= c->reader->maxbuf && !c->err && !ac->err && !c->reader->err) {
    redis_nginx_read_event(ev);
  }
```

**Comment by slact** [comment] 2016-08-29 06:50
```c
if (c->reader->len >= c->reader->maxbuf && !c->err && !ac->err && !c->reader->err) {
    redis_nginx_read_event(ev);
  }
```
That doesn't work reliably in my tests either. Anyway, it doesn't look like the `ioctl` call adds much overhead, especially compared to all the `realloc()`s hiredis is doing. So I'm adding it for now in 89dc98611999.  If this ends up being a bottleneck at some point, I'll modify hiredis.

**Comment by supertong** [comment] 2016-08-29 07:10
Thanks @slact . Working good!! Feel free to close this issue if you want. :)

**Comment by slact** [comment] 2016-08-29 07:12
Excellent. Thanks for the bug report.

**Closed by slact** 2016-08-29 07:12 UTC

**Comment by supertong** [comment] 2016-08-29 07:22
Another stupid question if you don't mind.
```
if msg.unbuffered or #msg.data < 5*1024 then
```
What was the reason to send only key id back if the data size is more than `5*1024`? It looks to me that it's quicker and easier if you send it back directly no matter of the data size? What's your concern here?

The reason I am asking is that I find out if I send request to change the queue size quickly, the message would be gone before Nchan try to get it with the key.

**Comment by slact** [comment] 2016-08-29 07:36
The issue I had in mind is keeping load off of the Redis server.

My biggest concern is msgpacking the incoming message into the PUBLISHed structure, which means alloc()ing and copying lots of data when the message is large.

Then, the PUBLISH data is sent to all subscribed Nchan instances. When a large message is sent, Redis will block while re-reading and sending to all subscribers. For small messages, this doesn't matter, but for large ones it adds up.

Whereas if you PUBLISH `msgkey` data, there is no msgpacking overhead, nor sending overhead.

I haven't benchmarked this very thoroughly, the limit is probably currently set too low. Perhaps there is also another solution, or maybe this is a case of premature optimization.

**Comment by supertong** [comment] 2016-08-29 07:53
Thanks! I will increase the value a bit according to our own use case and see how it goes.

**Comment by slact** [comment] 2016-08-29 07:54
Ok, don't forget to regenerate the lua commands header file with `rebuild.sh` in dev/

**Comment by supertong** [comment] 2016-08-29 09:50
Thanks! Didn't know there is a `rebuild.sh`. I used to do it with `hsss` manually which is simple enough too. :)

**Comment by slact** [comment] 2016-08-29 20:51
I've added a (hidden) config setting `nchan_redis_publish_msgpacked_max_size` in  8372f16 to set that value in the publish.lua script from the nginx config. I may wish to expose this later as an advanced performance tweaking option, but for now you can use it for your experiments.

**Comment by supertong** [comment] 2016-08-30 00:32
Thanks!! That's very handy.
