### ISSUE TITLE
Reloading nginx configuration files

### ISSUE THREAD

**Issue by Robinjoeh** [slact/nchan#118] opened 2015-12-29 10:53 UTC
There is an issue when reloading nginx configuration files. Doing so will mess up nchan's subscribe method (and probably the publish method as well). This is solved by restarting nginx completely. Can be reproduced each and every time, at least for me. The server is returning an unknown response when you try to subscribe to a channel.

**Comment by slact** [comment] 2016-01-13 22:58
I've been unable to reproduce this, and it seems that with an update the issue reporter is no longer seeing this issue. Closing.

**Closed by slact** 2016-01-13 22:58 UTC
