### ISSUE TITLE
publisher_upstream is not working for version above 1.1.7

### ISSUE THREAD

**Issue by abhishek4794** [slact/nchan#426] opened 2017-12-04 11:29 UTC
Here are my 2 location blocks
```nginx
location ~ /pub_init/(\w+)$ {
  nchan_publisher;
  nchan_publisher_upstream_request /upstream/pub;
  nchan_channel_id $1;
  nchan_message_buffer_length 0;
}

location ~ /sub/(\w+)$ {
  nchan_subscriber;
  nchan_channel_id $1;
}
```
I am calling one api on pub_init with publisher upstream.That api gives some response with http status code 200 , that response should be received by /sub location.
It is working fine for nchan version 1.1.7 but not working if I am upgrading nchan version

**Comment by slact** [comment] 2017-12-05 05:53
added tests for this in 942f0778, just to be sure this doesn't break in the future.

I need more information about what's happening in your case. Anything in the nginx error logs? What kind of upstream response is it?

**Comment by abhishek4794** [comment] 2017-12-05 06:03
Actually nothing in logs, thats why I am not able to understand what is actually going wrong.But one thing is sure, Same configuration is working fine for 1.1.7 and not for versions above.

**Comment by slact** [comment] 2017-12-05 06:05
Ok, I need to see your full config (edit out whatever you need for privacy), and a the upstream script or a few sample responses from it. You can post them here, or email me at leo@nchan.io. Or you can show me what's happening directly on your serve.r Email me for that as well.

**Comment by abhishek4794** [comment] 2017-12-05 06:29
Mailed you some more details.

**Comment by slact** [comment] 2018-06-28 03:17
Still unable to reproduce, and the original poster has found a workaround for his instance. Closing for now.

**Closed by slact** 2018-06-28 03:17 UTC
