### ISSUE TITLE
Install Guides and JS/HTML Code Example

### ISSUE THREAD

**Issue by bgildea** [slact/nchan#326] opened 2017-03-18 07:47 UTC
**Background/Reason**

I think that adding some quick start guides might improve people's experience in getting started with Nchan?

**Request**
- I would like to request a simple how to guide example of getting going with push using the javascript NchanSubscriber.js and HTML or PHP etc. with the Nginx config settings included below....
- It would be just a simple text message sent from one page and received on another page.

**NGINX Config:**
server {
    listen       80;
    server_name  localhost;
    ...
    location / {
        root   /usr/share/nginx/html;
        index  index.php index.html index.htm;
    }
    #Add following lines
    location = /sub {
      nchan_subscriber;
      nchan_channel_id $arg_id;
    }
    location = /pub {
      nchan_publisher;
      nchan_channel_id $arg_id;
    }
...

Thank you for your great work on this...

**Comment by slact** [comment] 2017-03-19 07:11
Not sure why you closed this, a simple getting-started example would be pretty useful. The problem is, of course, getting people to build Nginx properly. I've avoided this mostly because there are already many guides out there for this, but I might want to link for one or two.

**Comment by bgildea** [comment] 2017-03-19 07:15
Yes I agree... Closed because I thought it might be too rudimentary. Apologies.

I am going to build a simple HTML example and I will share it back once it works for me.

I may also create an issue outlining my issues installing for Debian Jessie (and my solution)

**Comment by bgildea** [comment] 2017-03-19 14:21
I am making progress with individual websocket and event Source examples working.
Websocket times out and I expect I have to set that in config as nchan_websocket_ping_interval ?

Can you give me guidance on setting up and using the NchanSubscriber.js for myIpAddress/sub in a web page? An example config that falls back to the other protocols for browsers?

**Comment by bgildea** [comment] 2017-03-20 08:38
I got NchanSubscriber.js working using the following HTML and Javascript.

This helped: https://github.com/slact/nchan/issues/179

What's the best order for fallback and browser compatibility & stay alive in your opinion?

e.g var sub = new NchanSubscriber(url, 'longpoll', 'eventsource', 'websocket');

I would like to help write a simple guide for a few ways to get up an running for the project using different front-end technique.

**Publish Page in HTML**

There is a better version of a publish page that formats the text properly here: https://codepen.io/matt-west/pen/tHlBb

```
<!DOCTYPE HTML>
<html>
<body>
<p>Post Example - Publish a Message</p>
<form action="/pub" method="post">
Message:</br>
<textarea rows="4" cols="50" name="message"></textarea></br>
<input type="submit">
</form>
</body>
</html>
```

**Listener / Subscription Page in HTML / JS**

```
<!DOCTYPE HTML>
 <meta charset="utf-8" />
<html>
<head>
  <script type="text/javascript" src="NchanSubscriber.js"></script>
</head>
<body>
  <p>Using the NchanSubscriber.js </p></br>
<script>
var url = "http://MyIPAddress:80/sub";
var sub = new NchanSubscriber(url, 'longpoll', 'eventsource', 'websocket');
sub.on("message", function(message, message_metadata) {
//alert(message);
document.write(message + "<br>");
});
sub.start();
</script>
<body>
</html>
```

 **NGINX Config**

NGINX Config:
server {
listen 80;
server_name localhost;
...
location / {
root /usr/share/nginx/html;
index index.php index.html index.htm;
}
#Add following lines
location = /sub {
nchan_subscriber;
nchan_channel_id $arg_id;
}
location = /pub {
nchan_publisher;
nchan_channel_id $arg_id;
}

**Comment by bgildea** [comment] 2017-03-20 10:25
I don't think this is falling back properly. I tried it on IE 10 and my subscription page didn't work.
Is my syntax and implementation ok?
var sub = new NchanSubscriber(url, 'longpoll', 'eventsource', 'websocket');

I am considering (only using EventSource) using a polyfill for EventSource / SEE to support IE and  
https://github.com/remy/polyfills/blob/master/EventSource.js

**Comment by indatawetrust** [comment] 2017-03-21 23:43
https://github.com/indatawetrust/docker-nchan

**Comment by slact** [comment] 2017-03-22 00:57
> Is my syntax and implementation ok?
> `var sub = new NchanSubscriber(url, 'longpoll', 'eventsource', 'websocket');`

No, the subscriber types should be an array.
```js
var sub = new NchanSubscriber(url, {subscriber: ['longpoll', 'eventsource', 'websocket']});

//or shorthand as
var sub = new NchanSubscriber(url, ['longpoll', 'eventsource', 'websocket']);
```

**Comment by bgildea** [comment] 2017-03-22 02:19
Another subscriber page example with the SSE / Server Event Polyfill script from https://github.com/Yaffle/EventSource

``
<!DOCTYPE` html>
<html>
<head>
    <meta charset="utf-8" />
    <title>EventSource example</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <script src="eventsource.js"></script>
    <script>
      var es = new EventSource("http://34.250.116.215:80/sub");
      var listener = function (event) {
        var div = document.createElement("div");
        var type = event.type;
        div.appendChild(document.createTextNode(type + ": " + (type === "message" ? event.data : es.url)));
        document.body.appendChild(div);
      };
    //es.addEventListener("open", listener);
      es.addEventListener("message", listener);
    // es.addEventListener("error", listener);
    </script>
</head>
<body>
<h1>Event Source and polyfill for IE.</h1>
<p>https://github.com/Yaffle/EventSource</p>
</body>
</html>
``

**Closed** 2017-03-23 05:34 UTC

**Comment by MBuffenoir** [comment] 2017-04-27 08:59
The dockerfile from @indatawetrust  should end up in the install docs at it's a time save !

**Comment by slact** [comment] 2017-04-27 15:57
@MBuffenoir : noted, will add it for the next version bump.
