### ISSUE TITLE
msgid_to_str reuse previous output if it's used multiple times in a single statement.

### ISSUE THREAD

**Issue by supertong** [slact/nchan#259] opened 2016-09-15 05:26 UTC
Hey @slact , finally got sometime to look at Nchan again. I was trying to reproduce some production issues on my local but I found something else.

I was output some debug information in `spool_nextmsg` like following
```c
...

  ERR("TTT, we are in next message here, spool->id = %V, new_id = %V, new_id->time=%i", msgid_to_str(&spool->id), msgid_to_str(&new_id), new_id.time);
  if(msg_ids_equal(&spool->id, &new_id)) {
    ERR("nextmsg id same as curmsg (%V)", msgid_to_str(&spool->id));
    assert(0);
  }
  else {
...
```
And here is the output I get
```
2016/09/15 05:22:43 [error] 1438#0: SPOOL:TTT, we are in next message here, spool->id = 1473915834:0, new_id = 1473915834:0, new_id->time=1473916944
```
The `new_id` and `spool->id` has exactly the same output from `msgid_to_str`. This was confusing me for a while until I print out `new_id->time` and realized it could be the problem of function `msgid_to_str`. I see you are using `static` keywords for returning `ngx_str_t` and string buffer. I am not a C export, but I feel this is causing the problem. By the way, if I output the msg_id in different `ERR` statement, there is no such problem.

It could be compiler related too? I guess. My compiler version
```
/tmp/src/nginx-1.11.1 # gcc --version
gcc (Alpine 5.3.0) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Cheers

**Comment by slact** [comment] 2016-09-15 05:32
It's not compiler related, msgid_to_str is an ugly function. it writes the string to a static string buffer, and returns that. This makes it unsuitable for calling multiple times in a single statement (like an ERR() macro)

**Comment by supertong** [comment] 2016-09-15 06:11
Sounds like it's not a bug? Shall we just pay attention to this when we use it?

**Comment by slact** [comment] 2016-09-15 19:07
Yeah, it's not a bug, it's just a badly documented ugly function. I"m going to close this, and maybe add a few comments to the code about it until I clean it up properly.

**Closed** 2016-09-15 19:07 UTC
