### ISSUE TITLE
nginx reload drops current connections

### ISSUE THREAD

**Issue by kidd** [slact/nchan#290] opened 2016-12-12 10:18 UTC
Given this configuration (nothing strange there):

```
worker_processes  1;
master_process on;
#daemon off;

events {
    worker_connections  1024;
}


http {
    server {
        listen       8888;

        location ~ /sub {
            nchan_subscriber http-raw-stream;
            nchan_channel_id "foo";
        }

        location = /pub {
            nchan_publisher ;
            nchan_channel_id "foo";
        }
    }
}
```

- Connect via: `curl http://localhost:8888/sub`. 
- Reloading the conf `/tmp/nginx/sbin/nginx -p . -c ./conf/nginx.conf -s reload`
- The client is dropped.

Not sure if this is the expected behaviour, but it doesn't look great from the user perspective :p.  Is it expected?

Btw, Thanks for this great project :)

**Comment by slact** [comment] 2016-12-12 17:39
Yes, this is the expected behavior. I've looked into it, and persisting connections across reloads is feasible, but not easy. 

When Nginx reloads, it exists its old workers and spawns new ones with new configuration. Also, Nchan currently does not persist data across reloads (unless using Redis).

So in order for this to happen, the dying workers need to send all their subscriber's file descriptors,along with the incoming request data, to the new workers. In turn, those need to process this data as normal incoming requests, completely bypassing Nginx's normal request processing cycle. There is also the issue of the Nginx master process force-killing old workers that take too long to shut down.

So it's possible, but very tricky.

Generally speaking, subscribers should have some code to attempt reconnection. This is a very good idea because Nchan has no-loss, no-repeat reconnection semantics, and it also addresses the issue of transient network faults. EventSource, as implemented in all the browsers, reconnects automatically. Nchansubscriber.js tries to reconnect as well.

Maybe I can add no-drop reloading at some point down the road, but for the moment, failure-tolerant subscribers are the way to go.

**Comment by kidd** [comment] 2016-12-13 15:56
I thought when a reload happened the 'current' connexions were kept and new ones were taken by new workers (to achieve reload without downtime). For long connections it would be a bit more contrived than for 'normal' short lived connexions, but I thought the design of nginx would transfer ok to this use case with long connections.

As you said, clients should take care of reconnecting in case of closed connections, so it's not a major thing.  Feel free to close the issue with a WONTFIX if it's really not feasible.

**Comment by slact** [comment] 2016-12-13 20:42
The 'no-downtime' comes from Nginx not killing the old workers immediately, but waiting for them to finish their last queued requests. 

So yes, this is a WONTFIX for the moment. However, I may revisit this issue later on if there's a seriously compelling use case or Nginx internals change to make it more feasible. Thanks for your suggestion.

**Closed by slact** 2016-12-13 20:42 UTC

**Comment by phiresky** [comment] 2021-03-29 16:48
> So in order for this to happen, the dying workers need to send all their subscriber's file descriptors,along with the incoming request data, to the new workers. In turn, those need to process this data as normal incoming requests, completely bypassing Nginx's normal request processing cycle. There is also the issue of the Nginx master process force-killing old workers that take too long to shut down.

Can't the old workers just keep the connections alive until they are force-killed? I'm currently using pure long-running websockets proxied through nginx (without nchan), and when nginx is reloaded the old connections just stay alive within the old workers (until they are killed I guess, but that takes longer than the average user session. I've been evaluating using nchan instead for better pubsub performance, but my nginx configuration is reloaded fairly often (e.g. to reload fail2ban ip ban lists), and connections dropping out regularily for multiple seconds (EventSource reconnect delay) is kind of a blocking issue for me to use nchan.

**Comment by slact** [comment] 2021-04-15 21:46
@phiresky 
> Can't the old workers just keep the connections alive until they are force-killed?

In theory -- yes, but the Nginx master will kill them within 10 seconds, or whatever the hardcoded max. wait time is.

In practice -- the interprocess  communication system in Nchan is rather fragile, because it must strictly obey the rules of the Nginx worker lifecycle. Supporting dying workers in the IPC system is a non-trivial task.

**Comment by phiresky** [comment] 2021-04-15 21:52
> In theory -- yes, but the Nginx master will kill them within 10 seconds, or whatever the hardcoded max. wait time is.

I think if there was a wait time it has been increased significantly at some point. I didn't find any direct information in the nginx docs, but when I recently checked i had over 100 dying workers running on my production setup  (which has very-long lived websocket connections) from multiple restarts over the course of hours

Not saying it's easy to implement of course, just saying that for my setup it's probably not acceptable to drop connections when reloading the configuration (but dropping connections older than an hour is fine)
