### ISSUE TITLE
Causing nginx errors of without puting channel_id args in quotation marks

### ISSUE THREAD

**Issue by argb** [slact/nchan#308] opened 2017-01-22 06:46 UTC
I got some nginx access errors like this:
2017/01/22 14:19:49 [alert] 95#0: worker process 388 exited on signal 11
2017/01/22 14:22:41 [error] 10129#0: MEMSTORE:00: tried adding WAITING chanhead 00007FF2322012E0 /wg to chanhead_gc. why?

curl error: 
curl: (52) Empty reply from server

The configure causing errors:
```nginx
location ~ /pub/(\w+)$ {
        #channel id is the word after /sub/
        # GET /sub/foobar_baz will have the channel id set to 'foobar_baz'
        # I hope you know your regular expressions...
        nchan_publisher;
        nchan_channel_id $1; #first capture of the location match
    }
```
When I put the symbol $1 in qoutation marks, like this nchan_channel_id "$1";, the errors gone.

**Comment by slact** [comment] 2017-01-22 13:46
What version of nginx and nchan are you using? Would you be able to give me a GDB backtrace?

**Comment by slact** [comment] 2017-10-05 22:55
I couldn't reproduce this issue. Closing this for now. Please reopen if you have any more information.

**Closed** 2017-10-05 23:00 UTC
