### ISSUE TITLE
Unavailable (out-of-memory) redis server on startup crashes Nchan

### ISSUE THREAD

**Issue by brunoqc** [slact/nchan#200] opened 2016-06-29 15:38 UTC
I don't know if redis crashed or only had errors. I don't know why I had these `Cannot allocate memory` errors.

nginx 1.11.1
nchan 0.99.16

```
Reading symbols from /usr/sbin/nginx...Reading symbols from /usr/lib/debug/.build-id/22/52597e56bb163e96e29c7a63ff78829cb2444d.debug...done.
bdone.
[New LWP 9915]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
Core was generated by `nginx: worker process                   '.
Program terminated with signal SIGABRT, Aborted.
#0  0xb7758428 in __kernel_vsyscall ()
(gdb) bt
#0  0xb7758428 in __kernel_vsyscall ()
#1  0xb7282687 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#2  0xb7285ab3 in __GI_abort () at abort.c:89
#3  0xb727b7c7 in __assert_fail_base (fmt=0xb73b8df4 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x81aa9c0 "0",
    file=file@entry=0x81ad160 "/home/bbigras/nginx/nginx-1.11.1/debian/modules/nchan/src/store/spool.c", line=line@entry=331,
    function=function@entry=0x81ad9ac <__PRETTY_FUNCTION__.26639> "spool_fetch_msg_callback") at assert.c:92
#4  0xb727b877 in __GI___assert_fail (assertion=assertion@entry=0x81aa9c0 "0", file=file@entry=0x81ad160 "/home/bbigras/nginx/nginx-1.11.1/debian/modules/nchan/src/store/spool.c", line=line@entry=331,
    function=function@entry=0x81ad9ac <__PRETTY_FUNCTION__.26639> "spool_fetch_msg_callback") at assert.c:101
#5  0x08152321 in spool_fetch_msg_callback (findmsg_status=MSG_NOTFOUND, msg=0x0, data=0x9bd7730) at /home/bbigras/nginx/nginx-1.11.1/debian/modules/nchan/src/store/spool.c:331
#6  0x0815ed00 in redis_get_message_callback (c=0x9cc14f0, r=0x9bd76a0, privdata=0x9bd51f0) at /home/bbigras/nginx/nginx-1.11.1/debian/modules/nchan/src/store/redis/rdsstore.c:1659
#7  0x081567a0 in __redisRunCallback (cb=0xbfe52cd4, cb=0xbfe52cd4, reply=<optimized out>, ac=0x9cc14f0) at /home/bbigras/nginx/nginx-1.11.1/debian/modules/nchan/src/hiredis/async.c:269
#8  redisProcessCallbacks (ac=0x9cc14f0) at /home/bbigras/nginx/nginx-1.11.1/debian/modules/nchan/src/hiredis/async.c:469
#9  0x0807feec in ngx_event_process_posted (cycle=<optimized out>, cycle@entry=0x9ac2628, posted=<optimized out>) at src/event/ngx_event_posted.c:33
#10 0x0807faba in ngx_process_events_and_timers (cycle=cycle@entry=0x9ac2628) at src/event/ngx_event.c:259
#11 0x08086216 in ngx_worker_process_cycle (cycle=0x9ac2628, data=0x1) at src/os/unix/ngx_process_cycle.c:753
#12 0x08084c46 in ngx_spawn_process (cycle=cycle@entry=0x9ac2628, proc=proc@entry=0x8086190 <ngx_worker_process_cycle>, data=data@entry=0x1, name=name@entry=0x8174f9f "worker process",
    respawn=respawn@entry=-4) at src/os/unix/ngx_process.c:198
#13 0x080863f3 in ngx_start_worker_processes (cycle=cycle@entry=0x9ac2628, n=2, type=type@entry=-4) at src/os/unix/ngx_process_cycle.c:358
#14 0x08086eb7 in ngx_master_process_cycle (cycle=0x9ac2628, cycle@entry=0x9ab3548) at src/os/unix/ngx_process_cycle.c:243
#15 0x080639ae in main (argc=3, argv=0xbfe53114) at src/core/nginx.c:367
```

error.log
```
2016/06/29 11:05:37 [notice] 9889#9889: http_auth_ldap: parse_require in /etc/nginx/sites-enabled/git.app.local:5
2016/06/29 11:05:37 [notice] 9889#9889: http_auth_ldap: Setting group in /etc/nginx/sites-enabled/git.app.local:5
2016/06/29 11:05:37 [notice] 9889#9889: http_auth_ldap: parse_require in /etc/nginx/sites-enabled/git.app.local:14
2016/06/29 11:05:37 [notice] 9889#9889: http_auth_ldap: Setting group in /etc/nginx/sites-enabled/git.app.local:14
2016/06/29 11:05:37 [info] 9889#9889: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/06/29 11:05:43 [alert] 8825#8825: *62410 open socket #11 left in connection 3
2016/06/29 11:05:43 [alert] 8825#8825: *62412 open socket #12 left in connection 4
2016/06/29 11:05:43 [alert] 8825#8825: aborting
2016/06/29 11:05:56 [error] 8824#8824: MEMSTORE:02: force-reaping msg with refcount 1
2016/06/29 11:05:56 [error] 8824#8824: MEMSTORE:02: force-reaping msg with refcount 1
2016/06/29 11:05:56 [alert] 8824#8824: *62411 open socket #9 left in connection 3
2016/06/29 11:05:56 [alert] 8824#8824: *62413 open socket #10 left in connection 4
2016/06/29 11:05:56 [alert] 8824#8824: aborting
2016/06/29 11:07:02 [notice] 10215#10215: http_auth_ldap: parse_require in /etc/nginx/sites-enabled/git.app.local:5
2016/06/29 11:07:02 [notice] 10215#10215: http_auth_ldap: Setting group in /etc/nginx/sites-enabled/git.app.local:5
2016/06/29 11:07:02 [notice] 10215#10215: http_auth_ldap: parse_require in /etc/nginx/sites-enabled/git.app.local:14
2016/06/29 11:07:02 [notice] 10215#10215: http_auth_ldap: Setting group in /etc/nginx/sites-enabled/git.app.local:14
2016/06/29 11:07:02 [info] 10215#10215: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/06/29 11:09:11 [error] 9914#9914: REDIS SCRIPT ERROR: publish : @user_script:124: @user_script: 124: -MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
2016/06/29 11:09:12 [error] 9915#9915: REDIS SCRIPT ERROR: publish : @user_script:124: @user_script: 124: -MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
2016/06/29 11:09:12 [error] 9914#9914: REDIS SCRIPT ERROR: add_fakesub : @user_script:20: @user_script: 20: -MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
2016/06/29 11:09:12 [alert] 2579#2579: worker process 2581 exited on signal 9
2016/06/29 11:09:12 [error] 9914#9914: REDIS SCRIPT ERROR: add_fakesub : @user_script:20: @user_script: 20: -MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
2016/06/29 11:09:13 [error] 9915#9915: REDIS SCRIPT ERROR: subscriber_register : @user_script:35: @user_script: 35: -MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
2016/06/29 11:09:13 [error] 9915#9915: REDIS SCRIPT ERROR: subscriber_register : @user_script:35: @user_script: 35: -MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
2016/06/29 11:09:13 [error] 9915#9915: SPOOL:Unexpected spool == nuspool during spool fetch_msg_callback. This is weird, please report this to the developers. findmsg_status: 4
ker process: /home/bbigras/nginx/nginx-1.11.1/debian/modules/nchan/src/store/spool.c:331: spool_fetch_msg_callback: Assertion `0' failed.
2016/06/29 11:09:14 [error] 9914#9914: REDIS SCRIPT ERROR: add_fakesub : @user_script:20: @user_script: 20: -MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
2016/06/29 11:09:14 [error] 9914#9914: REDIS SCRIPT ERROR: add_fakesub : @user_script:20: @user_script: 20: -MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
2016/06/29 11:09:21 [error] 9914#9914: REDIS SCRIPT ERROR: add_fakesub : @user_script:20: @user_script: 20: -MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
2016/06/29 11:09:26 [alert] 2579#2579: worker process 9915 exited on signal 6 (core dumped)
2016/06/29 11:09:26 [error] 10748#10748: IPC:got IPC alert delayed by 5 sec
2016/06/29 11:09:26 [error] 10748#10748: IPC:got IPC alert delayed by 4 sec
2016/06/29 11:09:52 [notice] 10939#10939: http_auth_ldap: parse_require in /etc/nginx/sites-enabled/git.app.local:5
2016/06/29 11:09:52 [notice] 10939#10939: http_auth_ldap: Setting group in /etc/nginx/sites-enabled/git.app.local:5
2016/06/29 11:09:52 [notice] 10939#10939: http_auth_ldap: parse_require in /etc/nginx/sites-enabled/git.app.local:14
2016/06/29 11:09:52 [notice] 10939#10939: http_auth_ldap: Setting group in /etc/nginx/sites-enabled/git.app.local:14
2016/06/29 11:09:52 [info] 10939#10939: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:83
2016/06/29 11:09:52 [alert] 2580#2580: *1 open socket #59 left in connection 3
2016/06/29 11:09:52 [alert] 2580#2580: *2 open socket #60 left in connection 4
2016/06/29 11:09:52 [alert] 2580#2580: *5 open socket #63 left in connection 8
2016/06/29 11:09:52 [alert] 2580#2580: *35 open socket #70 left in connection 13
2016/06/29 11:09:52 [alert] 2580#2580: *61303 open socket #103 left in connection 16
2016/06/29 11:09:52 [alert] 2580#2580: *42 open socket #75 left in connection 18
2016/06/29 11:09:52 [alert] 2580#2580: *50629 open socket #77 left in connection 22
2016/06/29 11:09:52 [alert] 2580#2580: *61 open socket #82 left in connection 25
2016/06/29 11:09:52 [alert] 2580#2580: *58248 open socket #90 left in connection 28
2016/06/29 11:09:52 [alert] 2580#2580: *49363 open socket #87 left in connection 38
2016/06/29 11:09:52 [alert] 2580#2580: *58249 open socket #96 left in connection 39
2016/06/29 11:09:52 [alert] 2580#2580: *50634 open socket #92 left in connection 43
2016/06/29 11:09:52 [alert] 2580#2580: *61302 open socket #102 left in connection 49
2016/06/29 11:09:52 [alert] 2580#2580: aborting
```

redis log
```
5322:C 29 Jun 10:52:59.466 * RDB: 20 MB of memory used by copy-on-write
2625:M 29 Jun 10:52:59.553 * Background saving terminated with success
2625:M 29 Jun 10:58:00.041 * 10 changes in 300 seconds. Saving...
2625:M 29 Jun 10:58:00.050 * Background saving started by pid 7056
7056:C 29 Jun 10:58:05.641 * DB saved on disk
7056:C 29 Jun 10:58:05.644 * RDB: 20 MB of memory used by copy-on-write
2625:M 29 Jun 10:58:05.676 * Background saving terminated with success
2625:M 29 Jun 11:03:06.086 * 10 changes in 300 seconds. Saving...
2625:M 29 Jun 11:03:06.094 * Background saving started by pid 8768
8768:C 29 Jun 11:03:11.630 * DB saved on disk
8768:C 29 Jun 11:03:11.634 * RDB: 16 MB of memory used by copy-on-write
2625:M 29 Jun 11:03:11.722 * Background saving terminated with success
2625:M 29 Jun 11:08:12.110 * 10 changes in 300 seconds. Saving...
2625:M 29 Jun 11:08:12.148 # Can't save in background: fork: Cannot allocate memory
2625:M 29 Jun 11:08:18.057 * 10 changes in 300 seconds. Saving...
2625:M 29 Jun 11:08:18.076 # Can't save in background: fork: Cannot allocate memory
2625:M 29 Jun 11:08:24.057 * 10 changes in 300 seconds. Saving...
2625:M 29 Jun 11:08:24.073 # Can't save in background: fork: Cannot allocate memory
2625:M 29 Jun 11:08:30.081 * 10 changes in 300 seconds. Saving...
2625:M 29 Jun 11:08:30.092 # Can't save in background: fork: Cannot allocate memory
2625:M 29 Jun 11:08:36.085 * 10 changes in 300 seconds. Saving...
2625:M 29 Jun 11:08:36.096 # Can't save in background: fork: Cannot allocate memory
2625:M 29 Jun 11:08:42.150 * 10 changes in 300 seconds. Saving...
2625:M 29 Jun 11:08:42.201 # Can't save in background: fork: Cannot allocate memory
2625:M 29 Jun 11:08:49.541 * 10 changes in 300 seconds. Saving...
2625:M 29 Jun 11:08:51.265 # Can't save in background: fork: Cannot allocate memory
2625:M 29 Jun 11:08:58.500 * 10 changes in 300 seconds. Saving...
2625:M 29 Jun 11:08:59.484 # Can't save in background: fork: Cannot allocate memory
2625:M 29 Jun 11:09:07.100 * 10 changes in 300 seconds. Saving...
2625:M 29 Jun 11:09:08.362 # Can't save in background: fork: Cannot allocate memory
2625:M 29 Jun 11:09:13.077 * 10 changes in 300 seconds. Saving...
2625:M 29 Jun 11:09:13.087 * Background saving started by pid 10542
10542:C 29 Jun 11:09:26.426 * DB saved on disk
10542:C 29 Jun 11:09:26.429 * RDB: 16 MB of memory used by copy-on-write
2625:M 29 Jun 11:09:26.536 * Background saving terminated with success
2625:M 29 Jun 11:14:27.093 * 10 changes in 300 seconds. Saving...
2625:M 29 Jun 11:14:27.100 * Background saving started by pid 12445
12445:C 29 Jun 11:14:32.809 * DB saved on disk
12445:C 29 Jun 11:14:32.814 * RDB: 18 MB of memory used by copy-on-write
2625:M 29 Jun 11:14:32.935 * Background saving terminated with success
```

**Comment by brunoqc** [comment] 2016-06-29 15:50
I had a huge spike in memory usage. I don't know what was the cause.

**Comment by slact** [comment] 2016-06-29 15:53
Not sure about the memory spike, but Nchan did not handle Redis unavailability correctly -- crashing is rarely the correct behavior...

**Comment by brunoqc** [comment] 2016-06-29 19:39
The memory spike wasn't caused by redis nor nchan. postrgresql went crazy.

**Comment by brunoqc** [comment] 2016-07-18 15:01
I still had the problem this morning.

**Comment by slact** [comment] 2016-07-18 19:59
This is going to be address in the next release, which will include a lot of reworked Redis code and support for clusters and per-location redis servers. I expect to have it ready in a week or two.

**Comment by slact** [comment] 2016-08-29 03:45
Are you still experiencing this problem? I couldn't reproduce this crash using the current code in master.

**Comment by brunoqc** [comment] 2016-08-29 13:55
I didn't upgrade yet. I tried once but I had weird errors (maybe not related to nchan). I was waiting for an opportunity where it wouldn't affect users while I checked. I'll try on the lunch break today.

**Comment by brunoqc** [comment] 2016-08-29 16:02
I have the same problem. It's weird that I didn't have this problem when I tested nchan+redis with docker for another bug report.

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  ngx_strnstr (s1=s1@entry=0x0, s2=0x835e1e0 "edis://", s2@entry=0x835e1df "redis://", len=7, len@entry=8) at src/core/ngx_string.c:641
641                 c1 = *s1++;
(gdb) bt
#0  ngx_strnstr (s1=s1@entry=0x0, s2=0x835e1e0 "edis://", s2@entry=0x835e1df "redis://", len=7, len@entry=8) at src/core/ngx_string.c:641
#1  0x0819a37c in parse_redis_url (url=url@entry=0x87626bc, rcp=rcp@entry=0xbfaac2a8) at /home/bbigras/nginx/nginx-1.11.3/debian/modules/nchan-1.0.1/src/store/redis/rdsstore.c:176
#2  0x081a0243 in redis_add_connection_data (rcf=rcf@entry=0x87626bc, lcf=0x87625c0, override_url=override_url@entry=0x0)
    at /home/bbigras/nginx/nginx-1.11.3/debian/modules/nchan-1.0.1/src/store/redis/rdsstore.c:2279
#3  0x081a03af in nchan_store_init_postconfig (cf=0xbfaac5fc) at /home/bbigras/nginx/nginx-1.11.3/debian/modules/nchan-1.0.1/src/store/redis/rdsstore.c:2323
#4  0x081ac588 in nchan_postconfig (cf=0xbfaac5fc) at /home/bbigras/nginx/nginx-1.11.3/debian/modules/nchan-1.0.1/src/nchan_setup.c:51
#5  0x080c01ad in ngx_http_block (cf=0xbfaac5fc, cmd=0x84179a0 <ngx_http_commands>, conf=0x8760ad8) at src/http/ngx_http.c:308
#6  0x080a3530 in ngx_conf_handler (last=1, cf=0xbfaac5fc) at src/core/ngx_conf_file.c:427
#7  ngx_conf_parse (cf=cf@entry=0xbfaac5fc, filename=filename@entry=0x876031c) at src/core/ngx_conf_file.c:283
#8  0x080a0cc7 in ngx_init_cycle (old_cycle=old_cycle@entry=0xbfaac78c) at src/core/ngx_cycle.c:274
#9  0x0808fb0a in main (argc=3, argv=0xbfaac954) at src/core/nginx.c:276
```

**Comment by slact** [comment] 2016-08-29 16:21
That sounds like a different issue. Let's take it over to #241

**Comment by brunoqc** [comment] 2016-08-29 18:37
> Are you still experiencing this problem? I couldn't reproduce this crash using the current code in master.

It pretty rare that oom-killer had to do its thing. It didn't happen since last time.

Where you able to reproduce this bug before? Maybe I could try to find a way to reproduce the redis crash but you could also close this bug and I'll re-open it if it happens again.

**Comment by slact** [comment] 2016-08-29 18:51
A lot of the redis error handling has changed since you first reported this. I haven't been able to crash it under the exact same conditions, but things like OOM errors don't trigger a crash in Nchan.

I'll close this for now, feel free to reopen if you encounter it again.

**Closed by slact** 2016-08-29 18:51 UTC
